version: '3.1'

services:
  client:
    build: .
    volumes:
      - './client:/app'
    ports:
      - '3000:3000'
    depends_on:
      - server

  server:
    build: .
    volumes:
      - './server:/app'
    ports:
      - '8888:8888'
